- name: "Parsing pvc data"
  set_fact:
    mig_dest_pvc_data: []
    mig_dest_adjusted_pvc_data: []
    adjustment_report: []

- name: "Set fact for collection pvc errors"
  set_fact:
    pvc_errors: []

- name: "Convert storage class"
  vars:
    mig_converted_sc:
      storage_class: "{{ mig_storage_class_mappings.get(item.storage_class+'_'+('RWX' if 'ReadWriteMany' in item.access_modes else ('ROX' if 'ReadOnlyMany' in item.access_modes else 'RWO')), item.storage_class)}}"
  set_fact:
    mig_dest_pvc_data: "{{ mig_dest_pvc_data + [(item | combine(mig_converted_sc, recursive=true))] }}"
  loop: "{{ pvcs }}"

- block:
  - name: "Check if adjustment report file exists"
    stat:
      path: "{{ pv_size_adjustment_report_path }}"
    register: adjustment_report_file

  - name: "Reading volume size adjustment report"
    set_fact:
      adjustment_report: "{{ lookup('file', pv_size_adjustment_report_path) | from_json }}"
    when: adjustment_report_file.stat.exists

  - include_tasks: tasks/adjustment-interaction.yml
    loop: "{{ mig_dest_pvc_data }}"
    loop_control:
      loop_var: original_pvc_data

- name: "Ensure the pvcs are created on destination"
  include_tasks: tasks/ensure-pvc.yml
  loop: "{{ mig_dest_adjusted_pvc_data }}"
  tags:
  - create_pvcs_on_destination

- name: "Dumping failed pvcs report"
  copy:
    content: "{{ pvc_errors | to_json }}"
    dest: "{{ output_dir }}/failed-pvcs.json"
  tags:
    - create_pvcs_on_destination
