---
- hosts: localhost
  vars_files:
    - vars/run-rsync.yml
    - vars/defaults.yml
  tasks:
    - import_tasks: ../common/assert-kubeconfig.yml
      tags:
      - assert_kubeconfig

    - import_tasks: ../common/assert-vars.yml

    - tags:
      - load_vars
      set_fact:
        pvc_data: "{{ lookup('file', pvc_data_filepath) | from_json }}"

    - name: "Ensuring certificate for stunnel"
      import_tasks: tasks/stunnel-certs.yml
      tags:
      - stunnel_certs

    - name: "Create pod and service"
      vars:
        pvc_namespace: "{{ item.namespace }}"
        pod_name: "{{ pvc_namespace }}"
        svc_name: "{{ pvc_namespace }}"
        route_name: "{{ pvc_namespace }}"
        rsyncd_config: "{{ pod_name }}"
        pvcs: "{{ item.pvcs }}"
      include_tasks: tasks/create-pod-service.yml
      with_items: "{{ pvc_data }}"
